### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by peter279k** [angeloskath/php-nlp-tools#48]
As title. 
I want to know whether this library supports the language (Chinese, Japanese and so on.).
Thanks.

**Comment by angeloskath** [comment]
Hi, the project is not very actively developed, not many new features have been added lately and the develop branch has not been merged with the master for a while but **it is maintained**.

Regarding, whether this library supports the Chinese and Japanese languages, you would probably have to write your own [tokenizers](http://php-nlp-tools.com/documentation/tokenizers.html) and maybe [stopwords lists, stemming etc](http://php-nlp-tools.com/documentation/transformations.html), but other than that there is no reason why the library won't be working with any language.

If you encounter problems, bugs, etc just open another issue.

Cheers,
Angelos

P.S.: I am closing this issue because I think I replied well enough to the question "Is the project alive?"
