### ISSUE TITLE
IR features?

### ISSUE THREAD

**Issue by jtejido** [angeloskath/php-nlp-tools#58]
Hi @angeloskath ,

I'd like to know if the package is open for IR related PRs. I'm studying IR related subjects and been using your package for NLP. I've made some changes on my [fork](https://github.com/jtejido/php-nlp-tools) that I would like to know if they'll be helpful for others in the field too (though I'm positive that the intended scope for the package is purely NLP).

I'd also like to know if there are current plans for implementing persistent data (trained models, indexes, etc.)

**Comment by angeloskath** [comment]
Hi,

Sure, I guess that they are related and could interest a lot of people. Regarding merging PRs and working on the library it will be very difficult for me to spend time before the 10th of Feb.

If you are interested we could discuss long term goals at around that date. Otherwise you can just do the PRs and I 'll look at them as soon as I can.

Thanks for you work!
Angelos

**Comment by jtejido** [comment]
Thanks @angeloskath.
